### ISSUE TITLE
Depurar el package.json

### ISSUE THREAD

**Issue by DanielIzquierdo** [PinkFLoyd92/softwareII#19]
quitar las dependencias o dev-dependencias que no se utilizan para nada en el proyecto

**Comment by DanielIzquierdo** [comment]
tratar de seguir las recomendaciones de los warnings, tratar de reducir esos mensajes al mínimo mientras la aplicación funcione correctamente.

**Comment by PinkFLoyd92** [comment]
@GAumala  depuro el package.json en el commit #32
