### ISSUE TITLE
No cambia el Estado del AppBar

### ISSUE THREAD

**Issue by DanielIzquierdo** [PinkFLoyd92/softwareII#21]
cuando se está reservando una habitación, si no se selecciona una fecha final de reservación y se cambia de vista usando el menú no cambia el estado del Appbar.
![image](https://cloud.githubusercontent.com/assets/8524266/16185024/7e1de1ec-3686-11e6-9679-9ce02041cd40.png)

**Comment by PinkFLoyd92** [comment]
@GAumala ya arreglo eso en el commit #30
